export const apiArray = {
  count: 767,
  entries: [
    {
      API: 'Cat Facts',
      Description: 'Daily cat facts',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://alexwohlbruck.github.io/cat-facts/',
      Category: 'Animals',
    },
    {
      API: 'Cataas',
      Description: 'Cat as a service (cats pictures and gifs)',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://cataas.com/',
      Category: 'Animals',
    },
    {
      API: 'catAPI',
      Description: 'Random pictures of cats',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://github.com/ThatCopy/catAPI/wiki/Usage',
      Category: 'Animals',
    },
    {
      API: 'Cats',
      Description: 'Pictures of cats from Tumblr',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://docs.thecatapi.com/',
      Category: 'Animals',
    },
    {
      API: 'Dog Facts',
      Description: 'Random dog facts',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://dukengn.github.io/Dog-facts-API/',
      Category: 'Animals',
    },
    {
      API: 'Dogs',
      Description: 'Based on the Stanford Dogs Dataset',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://dog.ceo/dog-api/',
      Category: 'Animals',
    },
    {
      API: 'HTTPCat',
      Description: 'Cat for every HTTP Status',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://http.cat/',
      Category: 'Animals',
    },
    {
      API: 'IUCN',
      Description: 'IUCN Red List of Threatened Species',
      Auth: 'apiKey',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://apiv3.iucnredlist.org/api/v3/docs',
      Category: 'Animals',
    },
    {
      API: 'Movebank',
      Description: 'Movement and Migration data of animals',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/movebank/movebank-api-doc',
      Category: 'Animals',
    },
    {
      API: 'RandomCat',
      Description: 'Random pictures of cats',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://aws.random.cat/meow',
      Category: 'Animals',
    },
    {
      API: 'RandomDog',
      Description: 'Random pictures of dogs',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://random.dog/woof.json',
      Category: 'Animals',
    },
    {
      API: 'RandomFox',
      Description: 'Random pictures of foxes',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://randomfox.ca/floof/',
      Category: 'Animals',
    },
    {
      API: 'RescueGroups',
      Description: 'Adoption',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://userguide.rescuegroups.org/display/APIDG/API+Developers+Guide+Home',
      Category: 'Animals',
    },
    {
      API: 'Shibe.Online',
      Description: 'Random pictures of Shiba Inu, cats or birds',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'http://shibe.online/',
      Category: 'Animals',
    },
    {
      API: 'AniList',
      Description: 'Anime discovery \u0026 tracking',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/AniList/ApiV2-GraphQL-Docs',
      Category: 'Anime',
    },
    {
      API: 'AnimeChan',
      Description: 'Anime quotes (over 10k+)',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://github.com/RocktimSaikia/anime-chan',
      Category: 'Anime',
    },
    {
      API: 'AnimeNewsNetwork',
      Description: 'Anime industry news',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.animenewsnetwork.com/encyclopedia/api.php',
      Category: 'Anime',
    },
    {
      API: 'Jikan',
      Description: 'Unofficial MyAnimeList API',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://jikan.moe',
      Category: 'Anime',
    },
    {
      API: 'Kitsu',
      Description: 'Anime discovery platform',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://kitsu.docs.apiary.io/',
      Category: 'Anime',
    },
    {
      API: 'MyAnimeList',
      Description: 'Anime and Manga Database and Community',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://myanimelist.net/clubs.php?cid=13727',
      Category: 'Anime',
    },
    {
      API: 'Shikimori',
      Description: 'Anime discovery, tracking, forum, rates',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://shikimori.one/api/doc',
      Category: 'Anime',
    },
    {
      API: 'Studio Ghibli',
      Description: 'Resources from Studio Ghibli films',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://ghibliapi.herokuapp.com',
      Category: 'Anime',
    },
    {
      API: 'What Anime',
      Description: 'Scan anime image to get specific detail',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://soruly.github.io/trace.moe/',
      Category: 'Anime',
    },
    {
      API: 'AbuseIPDB',
      Description: 'IP/domain/URL reputation',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://docs.abuseipdb.com/',
      Category: 'Anti-Malware',
    },
    {
      API: 'AlienVault Open Threat Exchange (OTX)',
      Description: 'IP/domain/URL reputation',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://otx.alienvault.com/api',
      Category: 'Anti-Malware',
    },
    {
      API: 'Google Safe Browsing',
      Description: 'Google Link/Domain Flagging',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developers.google.com/safe-browsing/',
      Category: 'Anti-Malware',
    },
    {
      API: 'Metacert',
      Description: 'Metacert Link Flagging',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://metacert.com/',
      Category: 'Anti-Malware',
    },
    {
      API: 'URLScan.io',
      Description: 'Scan and Analyse URLs',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://urlscan.io/about-api/',
      Category: 'Anti-Malware',
    },
    {
      API: 'VirusTotal',
      Description: 'VirusTotal File/URL Analysis',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.virustotal.com/en/documentation/public-api/',
      Category: 'Anti-Malware',
    },
    {
      API: 'PM2.5 Open Data Portal',
      Description: 'Open low-cost PM2.5 sensor data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://pm25.lass-net.org/#apis',
      Category: 'Environment',
    },
    {
      API: 'PM25.in',
      Description: 'Air quality of China',
      Auth: 'apiKey',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.pm25.in/api_doc',
      Category: 'Environment',
    },
    {
      API: 'PVWatts',
      Description: 'Energy production photovoltaic (PV) energy systems',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.nrel.gov/docs/solar/pvwatts/v6/',
      Category: 'Environment',
    },
    {
      API: 'UK Carbon Intensity',
      Description: 'The Official Carbon Intensity API for Great Britain developed by National Grid',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://carbon-intensity.github.io/api-definitions/#carbon-intensity-api-v1-0-0',
      Category: 'Environment',
    },
    {
      API: 'Eventbrite',
      Description: 'Find events',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.eventbrite.com/developer/v3/',
      Category: 'Events',
    },
    {
      API: 'Picatic',
      Description: 'Sell tickets anywhere',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link:
        'http://developer.picatic.com/?utm_medium=web\u0026utm_source=github\u0026utm_campaign=public-apis%20repo\u0026utm_content=toddmotto',
      Category: 'Events',
    },
    {
      API: 'Ticketmaster',
      Description: 'Search events, attractions, or venues',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'http://developer.ticketmaster.com/products-and-docs/apis/getting-started/',
      Category: 'Events',
    },
    {
      API: 'Abstract VAT Validation',
      Description: 'Validate VAT numbers and calculate VAT rates',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.abstractapi.com/vat-validation-rates-api',
      Category: 'Finance',
    },
    {
      API: 'Alpha Vantage',
      Description: 'Realtime and historical stock data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.alphavantage.co/',
      Category: 'Finance',
    },
    {
      API: 'IEX Cloud',
      Description: 'Realtime \u0026 Historical Stock and Market Data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://iexcloud.io/docs/api/',
      Category: 'Finance',
    },
    {
      API: 'IG',
      Description: 'Spreadbetting and CFD Market Data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://labs.ig.com/gettingstarted',
      Category: 'Finance',
    },
    {
      API: 'Intrinio',
      Description: 'A wide selection of financial data feeds',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://intrinio.com/',
      Category: 'Finance',
    },
    {
      API: 'marketstack',
      Description: 'Real-Time, Intraday \u0026 Historical Market Data API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://marketstack.com/',
      Category: 'Finance',
    },
    {
      API: 'Plaid',
      Description: 'Connect with users’ bank accounts and access transaction data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://plaid.com/',
      Category: 'Finance',
    },
    {
      API: 'Razorpay IFSC',
      Description: 'Indian Financial Systems Code (Bank Branch Codes)',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://ifsc.razorpay.com/',
      Category: 'Finance',
    },
    {
      API: 'Tradier',
      Description: 'US equity/option market data (delayed, intraday, historical)',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://developer.tradier.com',
      Category: 'Finance',
    },
    {
      API: 'Twelve Data',
      Description: 'Stock market data (real-time \u0026 historical)',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://twelvedata.com/',
      Category: 'Finance',
    },
    {
      API: 'YNAB',
      Description: 'Budgeting \u0026 Planning',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://api.youneedabudget.com/',
      Category: 'Finance',
    },
    {
      API: 'Edamam nutrition',
      Description: 'Nutrition Analysis',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.edamam.com/edamam-docs-nutrition-api',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'Edamam recipes',
      Description: 'Recipe Search',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.edamam.com/edamam-docs-recipe-api',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'Foodish',
      Description: 'Random pictures of food dishes',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://github.com/surhud004/Foodish#readme',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'LCBO',
      Description: 'Alcohol',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://lcboapi.com/',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'Open Brewery DB',
      Description: 'Breweries, Cideries and Craft Beer Bottle Shops',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.openbrewerydb.org',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'Open Food Facts',
      Description: 'Food Products Database',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://world.openfoodfacts.org/data',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'PunkAPI',
      Description: 'Brewdog Beer Recipes',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://punkapi.com/',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'Recipe Puppy',
      Description: 'Food',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.recipepuppy.com/about/api/',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'Spoonacular',
      Description: 'Recipes and Food product',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://spoonacular.com/food-api',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'TacoFancy',
      Description: 'Community-driven taco database',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'https://github.com/evz/tacofancy-api',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'The Report of the Week',
      Description: 'Food \u0026 Drink Reviews',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/andyklimczak/TheReportOfTheWeek-API',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'TheCocktailDB',
      Description: 'Cocktail Recipes',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.thecocktaildb.com/api.php',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'TheMealDB',
      Description: 'Meal Recipes',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.themealdb.com/api.php',
      Category: 'Food \u0026 Drink',
    },
    {
      API: "What's on the menu?",
      Description: 'NYPL human-transcribed historical menu collection',
      Auth: 'apiKey',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://nypl.github.io/menus-api/',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'WhiskyHunter',
      Description: 'Past online whisky auctions statistical data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://whiskyhunter.net/api/',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'Zestful',
      Description: 'Parse recipe ingredients',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://zestfuldata.com/',
      Category: 'Food \u0026 Drink',
    },
    {
      API: 'Age of Empires II',
      Description: 'Get information about Age of Empires II resources',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://age-of-empires-2-api.herokuapp.com',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'AmiiboAPI',
      Description: 'Nintendo Amiibo Information',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://amiiboapi.com/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Board Game Geek',
      Description: 'Board games, RPG and videogames',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://boardgamegeek.com/wiki/page/BGG_XML_API2',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Brawl Stars',
      Description: 'Brawl Stars Game Information',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.brawlstars.com',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'CheapShark',
      Description: 'Steam/PC Game Prices and Deals',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.cheapshark.com/api',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Chuck Norris Database',
      Description: 'Jokes',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.icndb.com/api/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Clash of Clans',
      Description: 'Clash of Clans Game Information',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.clashofclans.com',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Clash Royale',
      Description: 'Clash Royale Game Information',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.clashroyale.com',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Comic Vine',
      Description: 'Comics',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://comicvine.gamespot.com/api/documentation',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Dark Souls 3',
      Description: 'Information about Dark Souls 3 Items',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://blog.mugenmonkey.com/2017/09/10/ds3-api.html',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Deck of Cards',
      Description: 'Deck of Cards',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://deckofcardsapi.com/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Destiny The Game',
      Description: 'Bungie Platform API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/Bungie-net/api',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Dota 2',
      Description: 'Provides information about Player stats , Match stats, Rankings for Dota 2',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://docs.opendota.com/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Dungeons and Dragons',
      Description: 'Reference for 5th edition spells, classes, monsters, and more',
      Auth: '',
      HTTPS: false,
      Cors: 'no',
      Link: 'http://www.dnd5eapi.co/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Eve Online',
      Description: 'Third-Party Developer Documentation',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://esi.evetech.net/ui',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'FIFA Ultimate Team',
      Description: 'FIFA Ultimate Team items API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.easports.com/fifa/ultimate-team/api/fut/item',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Final Fantasy XIV',
      Description: 'Final Fantasy XIV Game data API',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://xivapi.com/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Fortnite',
      Description: 'Fortnite Stats',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://fortnitetracker.com/site-api',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Giant Bomb',
      Description: 'Video Games',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.giantbomb.com/api/documentation',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Guild Wars 2',
      Description: 'Guild Wars 2 Game Information',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://wiki.guildwars2.com/wiki/API:Main',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Halo',
      Description: 'Halo 5 and Halo Wars 2 Information',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.haloapi.com/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Hearthstone',
      Description: 'Hearthstone Cards Information',
      Auth: 'X-Mashape-Key',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'http://hearthstoneapi.com/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Humble Bundle',
      Description: "Humble Bundle's current bundles",
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://rapidapi.com/Ziggoto/api/humble-bundle',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Hypixel',
      Description: 'Hypixel player stats',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.hypixel.net/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Hyrule Compendium',
      Description: 'Data on all interactive items from The Legend of Zelda: BOTW',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/gadhagod/Hyrule-Compendium-API',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Hytale',
      Description: 'Hytale blog posts and jobs',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://hytale-api.com/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'IGDB.com',
      Description: 'Video Game Database',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.igdb.com/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'JokeAPI',
      Description: 'Programming, Miscellaneous and Dark Jokes',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://sv443.net/jokeapi/v2/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Jokes',
      Description: 'Programming and general jokes',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/15Dkatz/official_joke_api',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Jokes One',
      Description: 'Joke of the day and large category of jokes accessible via REST API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://jokes.one/api/joke/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Jservice',
      Description: 'Jeopardy Question Database',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://jservice.io',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Lichess',
      Description: 'Access to all data of users, games, puzzles and etc on Lichess',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://lichess.org/api',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Magic The Gathering',
      Description: 'Magic The Gathering Game Information',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://magicthegathering.io/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Marvel',
      Description: 'Marvel Comics',
      Auth: 'apiKey',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://developer.marvel.com',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'mod.io',
      Description: 'Cross Platform Mod API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://docs.mod.io',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Open Trivia',
      Description: 'Trivia Questions',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://opentdb.com/api_config.php',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'PandaScore',
      Description: 'E-sports games and results',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developers.pandascore.co/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: "PlayerUnknown's Battlegrounds",
      Description: 'PUBG Stats',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://pubgtracker.com/site-api',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Pokéapi',
      Description: 'Pokémon Information',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://pokeapi.co',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Pokémon TCG',
      Description: 'Pokémon TCG Information',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://pokemontcg.io',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Random Facts',
      Description: 'Random Facts from hundreds of categories',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://fungenerators.com/api/facts/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Rick and Morty',
      Description: 'All the Rick and Morty information, including images',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://rickandmortyapi.com',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Riot Games',
      Description: 'League of Legends Game Information',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.riotgames.com/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Scryfall',
      Description: 'Magic: The Gathering database',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://scryfall.com/docs/api',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Steam',
      Description: 'Steam Client Interaction',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.valvesoftware.com/wiki/Steam_Web_API',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'SuperHeroes',
      Description: 'All SuperHeroes and Villains data from all universes under a single API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://superheroapi.com',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Tronald Dump',
      Description: 'The dumbest things Donald Trump has ever said',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.tronalddump.io/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Wargaming.net',
      Description: 'Wargaming.net info and stats',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://developers.wargaming.net/',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'xkcd',
      Description: 'Retrieve xkcd comics as JSON',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://xkcd.com/json.html',
      Category: 'Games \u0026 Comics',
    },
    {
      API: 'Abstract IP Geolocation',
      Description: 'Geolocate website visitors from their IPs',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.abstractapi.com/ip-geolocation-api',
      Category: 'Geocoding',
    },
    {
      API: 'adresse.data.gouv.fr',
      Description: 'Address database of France, geocoding and reverse',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://adresse.data.gouv.fr',
      Category: 'Geocoding',
    },
    {
      API: 'Airtel IP',
      Description: 'IP Geolocation API. Collecting data from multiple sources',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://sys.airtel.lv/ip2country/1.1.1.1/?full=true',
      Category: 'Geocoding',
    },
    {
      API: 'apilayer ipstack',
      Description: 'Locate and identify website visitors by IP address',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://ipstack.com/',
      Category: 'Geocoding',
    },
    {
      API: 'Battuta',
      Description: 'A (country/region/city) in-cascade location API',
      Auth: 'apiKey',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://battuta.medunes.net',
      Category: 'Geocoding',
    },
    {
      API: 'BigDataCloud',
      Description:
        'Provides fast and accurate IP geolocation APIs along with security checks and confidence area',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.bigdatacloud.com/ip-geolocation-apis',
      Category: 'Geocoding',
    },
    {
      API: 'Bing Maps',
      Description: 'Create/customize digital maps based on Bing Maps data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.microsoft.com/maps/',
      Category: 'Geocoding',
    },
    {
      API: 'bng2latlong',
      Description:
        'Convert British OSGB36 easting and northing (British National Grid) to WGS84 latitude and longitude',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.getthedata.com/bng2latlong',
      Category: 'Geocoding',
    },
    {
      API: 'Cep.la',
      Description:
        'Brazil RESTful API to find information about streets, zip codes, neighborhoods, cities and states',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://cep.la/',
      Category: 'Geocoding',
    },
    {
      API: 'CitySDK',
      Description: 'Open APIs for select European cities',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'http://www.citysdk.eu/citysdk-toolkit/',
      Category: 'Geocoding',
    },
    {
      API: 'Country',
      Description: "Get your visitors' country from their IP",
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'http://country.is/',
      Category: 'Geocoding',
    },
    {
      API: 'Daum Maps',
      Description: 'Daum Maps provide multiple APIs for Korean maps',
      Auth: 'apiKey',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://apis.map.daum.net/',
      Category: 'Geocoding',
    },
    {
      API: 'FreeGeoIP',
      Description: 'Free geo ip information, no registration required. 15k/hour rate limit',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://freegeoip.app/',
      Category: 'Geocoding',
    },
    {
      API: 'GeoApi',
      Description: 'French geographical data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.gouv.fr/api/geoapi.html',
      Category: 'Geocoding',
    },
    {
      API: 'Geoapify',
      Description: 'Forward and reverse geocoding, address autocomplete',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.geoapify.com/api/geocoding-api/',
      Category: 'Geocoding',
    },
    {
      API: 'Geocod.io',
      Description: 'Address geocoding / reverse geocoding in bulk',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.geocod.io/',
      Category: 'Geocoding',
    },
    {
      API: 'Geocode.xyz',
      Description: 'Provides worldwide forward/reverse geocoding, batch geocoding and geoparsing',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://geocode.xyz/api',
      Category: 'Geocoding',
    },
    {
      API: 'Geocodify.com',
      Description: 'Worldwide geocoding, geoparsing and autocomplete for addresses',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://geocodify.com/',
      Category: 'Geocoding',
    },
    {
      API: 'GeoDataSource',
      Description: 'Geocoding of city name by using latitude and longitude coordinates',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.geodatasource.com/web-service',
      Category: 'Geocoding',
    },
    {
      API: 'GeoJS',
      Description: 'IP geolocation with ChatOps integration',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://geojs.io/',
      Category: 'Geocoding',
    },
    {
      API: 'GeoNames',
      Description: 'Place names and other geographical data',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.geonames.org/export/web-services.html',
      Category: 'Geocoding',
    },
    {
      API: 'geoPlugin',
      Description: 'IP geolocation and currency conversion',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.geoplugin.com',
      Category: 'Geocoding',
    },
    {
      API: 'Google Earth Engine',
      Description: 'A cloud-based platform for planetary-scale environmental data analysis',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developers.google.com/earth-engine/',
      Category: 'Geocoding',
    },
    {
      API: 'Google Maps',
      Description: 'Create/customize digital maps based on Google Maps data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developers.google.com/maps/',
      Category: 'Geocoding',
    },
    {
      API: 'Graph Countries',
      Description:
        'Country-related data like currencies, languages, flags, regions+subregions and bordering countries',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/lennertVanSever/graphcountries',
      Category: 'Geocoding',
    },
    {
      API: 'HelloSalut',
      Description: 'Get hello translation following user language',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.fourtonfish.com/hellosalut/hello/',
      Category: 'Geocoding',
    },
    {
      API: 'HERE Maps',
      Description: 'Create/customize digital maps based on HERE Maps data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.here.com',
      Category: 'Geocoding',
    },
    {
      API: 'Hong Kong GeoData Store',
      Description: 'API for accessing geo-data of Hong Kong',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://geodata.gov.hk/gs/',
      Category: 'Geocoding',
    },
    {
      API: 'IP 2 Country',
      Description: 'Map an IP to a country',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://ip2country.info',
      Category: 'Geocoding',
    },
    {
      API: 'IP Address Details',
      Description: 'Find geolocation with ip address',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://ipinfo.io/',
      Category: 'Geocoding',
    },
    {
      API: 'IP Location',
      Description: 'Find IP address location information',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://ipapi.co/api/#introduction',
      Category: 'Geocoding',
    },
    {
      API: 'IP Location',
      Description: 'Find location with ip address',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'https://ip-api.com/docs',
      Category: 'Geocoding',
    },
    {
      API: 'IP Sidekick',
      Description: 'Geolocation API that returns extra information about an IP address',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://ipsidekick.com',
      Category: 'Geocoding',
    },
    {
      API: 'IP Vigilante',
      Description: 'Free IP Geolocation API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.ipvigilante.com/',
      Category: 'Geocoding',
    },
    {
      API: 'IP2Location',
      Description: 'IP geolocation web service to get more than 55 parameters',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.ip2location.com/web-service/ip2location',
      Category: 'Geocoding',
    },
    {
      API: 'IP2Proxy',
      Description: 'Detect proxy and VPN using IP address',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.ip2location.com/web-service/ip2proxy',
      Category: 'Geocoding',
    },
    {
      API: 'ipapi',
      Description: 'Real-time Geolocation \u0026 Reverse IP Lookup REST API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://ipapi.com/',
      Category: 'Geocoding',
    },
    {
      API: 'IPGEO',
      Description: 'Unlimited free IP Address API with useful information',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.techniknews.net/ipgeo/',
      Category: 'Geocoding',
    },
    {
      API: 'IPGeolocationAPI.com',
      Description: 'Locate your visitors by IP with country details',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://ipgeolocationapi.com/',
      Category: 'Geocoding',
    },
    {
      API: 'IPInfoDB',
      Description:
        'Free Geolocation tools and APIs for country, region, city and time zone lookup by IP address',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://ipinfodb.com/api',
      Category: 'Geocoding',
    },
    {
      API: 'Localizr',
      Description:
        'Get a list of countries,currencies or locales translated from a locale/language code',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://docs.localizr.xyz',
      Category: 'Geocoding',
    },
    {
      API: 'LocationIQ',
      Description: 'Provides forward/reverse geocoding and batch geocoding',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://locationiq.org/docs/',
      Category: 'Geocoding',
    },
    {
      API: 'Mapbox',
      Description: 'Create/customize beautiful digital maps',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.mapbox.com/developers/',
      Category: 'Geocoding',
    },
    {
      API: 'Mexico',
      Description: 'Mexico RESTful zip codes API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/IcaliaLabs/sepomex',
      Category: 'Geocoding',
    },
    {
      API: 'One Map, Singapore',
      Description: 'Singapore Land Authority REST API services for Singapore addresses',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://docs.onemap.sg/',
      Category: 'Geocoding',
    },
    {
      API: 'OnWater',
      Description: 'Determine if a lat/lon is on water or land',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://onwater.io/',
      Category: 'Geocoding',
    },
    {
      API: 'OpenCage',
      Description: 'Forward and reverse geocoding using open data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://opencagedata.com',
      Category: 'Geocoding',
    },
    {
      API: 'openrouteservice.org',
      Description: 'Directions, POIs, isochrones, geocoding (+reverse), elevation, and more',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://openrouteservice.org/',
      Category: 'Geocoding',
    },
    {
      API: 'OpenStreetMap',
      Description: 'Navigation, geolocation and geographical data',
      Auth: 'OAuth',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://wiki.openstreetmap.org/wiki/API',
      Category: 'Geocoding',
    },
    {
      API: 'positionstack',
      Description: 'Forward \u0026 Reverse Batch Geocoding REST API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://positionstack.com/',
      Category: 'Geocoding',
    },
    {
      API: 'PostcodeData.nl',
      Description: 'Provide geolocation data based on postcode for Dutch addresses',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link:
        'http://api.postcodedata.nl/v1/postcode/?postcode=1211EP\u0026streetnumber=60\u0026ref=domeinnaam.nl\u0026type=json',
      Category: 'Geocoding',
    },
    {
      API: 'Postcodes.io',
      Description: 'Postcode lookup \u0026 Geolocation for the UK',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://postcodes.io',
      Category: 'Geocoding',
    },
    {
      API: 'REST Countries',
      Description: 'Get information about countries via a RESTful API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://restcountries.eu',
      Category: 'Geocoding',
    },
    {
      API: 'SpotSense',
      Description: 'Add location based interactions to your mobile app',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.spotsense.io',
      Category: 'Geocoding',
    },
    {
      API: 'Uebermaps',
      Description: 'Discover and share maps with friends',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://uebermaps.com/api/v2',
      Category: 'Geocoding',
    },
    {
      API: 'US ZipCode',
      Description: 'Validate and append data for any US ZipCode',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://smartystreets.com/docs/cloud/us-zipcode-api',
      Category: 'Geocoding',
    },
    {
      API: 'Utah AGRC',
      Description: 'Utah Web API for geocoding Utah addresses',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.mapserv.utah.gov',
      Category: 'Geocoding',
    },
    {
      API: 'ViaCep',
      Description: 'Brazil RESTful zip codes API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://viacep.com.br',
      Category: 'Geocoding',
    },
    {
      API: 'ZipCodeAPI',
      Description: 'US zip code distance, radius and location API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.zipcodeapi.com',
      Category: 'Geocoding',
    },
    {
      API: 'Zippopotam.us',
      Description: 'Get information about place such as country, city, state, etc',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.zippopotam.us',
      Category: 'Geocoding',
    },
    {
      API: 'Ziptastic',
      Description: 'Get the country, state, and city of any US zip-code',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://ziptasticapi.com/',
      Category: 'Geocoding',
    },
    {
      API: 'BCLaws',
      Description: 'Access to the laws of British Columbia',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.bclaws.ca/civix/template/complete/api/index.html',
      Category: 'Government',
    },
    {
      API: 'Brazil Central Bank Open Data',
      Description: 'Brazil Central Bank Open Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://dadosabertos.bcb.gov.br/',
      Category: 'Government',
    },
    {
      API: 'BusinessUSA',
      Description: 'Authoritative information on U.S. programs, events, services and more',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://business.usa.gov/developer',
      Category: 'Government',
    },
    {
      API: 'Census.gov',
      Description:
        'The US Census Bureau provides various APIs and data sets on demographics and businesses',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.census.gov/data/developers/data-sets.html',
      Category: 'Government',
    },
    {
      API: 'City, Lyon Opendata',
      Description: 'Lyon(FR) City Open Data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://data.beta.grandlyon.com/fr/accueil',
      Category: 'Government',
    },
    {
      API: 'City, Nantes Opendata',
      Description: 'Nantes(FR) City Open Data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://data.nantesmetropole.fr/pages/home/',
      Category: 'Government',
    },
    {
      API: 'City, New York Opendata',
      Description: 'New York (US) City Open Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://opendata.cityofnewyork.us/',
      Category: 'Government',
    },
    {
      API: 'City, Prague Opendata',
      Description: 'Prague(CZ) City Open Data',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://opendata.praha.eu/en',
      Category: 'Government',
    },
    {
      API: 'Code.gov',
      Description:
        'The primary platform for Open Source and code sharing for the U.S. Federal Government',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://code.gov',
      Category: 'Government',
    },
    {
      API: 'Colorado Information Marketplace',
      Description: 'Colorado State Government Open Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://data.colorado.gov/',
      Category: 'Government',
    },
    {
      API: 'Data USA',
      Description: 'US Public Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://datausa.io/about/api/',
      Category: 'Government',
    },
    {
      API: 'Data.gov',
      Description: 'US Government Data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.data.gov/',
      Category: 'Government',
    },
    {
      API: 'Data.parliament.uk',
      Description:
        'Contains live datasets including information about petitions, bills, MP votes, attendance and more',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'https://explore.data.parliament.uk/?learnmore=Members',
      Category: 'Government',
    },
    {
      API: 'District of Columbia Open Data',
      Description:
        'Contains D.C. government public datasets, including crime, GIS, financial data, and so on',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'http://opendata.dc.gov/pages/using-apis',
      Category: 'Government',
    },
    {
      API: 'duma.gov.ru',
      Description: 'Russian State Duma Open Data',
      Auth: 'apiKey',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://api.duma.gov.ru',
      Category: 'Government',
    },
    {
      API: 'EPA',
      Description: 'Web services and data sets from the US Environmental Protection Agency',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.epa.gov/category/apis/',
      Category: 'Government',
    },
    {
      API: 'FBI Wanted',
      Description: 'Access information on the FBI Wanted program',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.fbi.gov/wanted/api',
      Category: 'Government',
    },
    {
      API: 'FEC',
      Description: 'Information on campaign donations in federal elections',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.open.fec.gov/developers/',
      Category: 'Government',
    },
    {
      API: 'Federal Register',
      Description: 'The Daily Journal of the United States Government',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.federalregister.gov/reader-aids/developer-resources',
      Category: 'Government',
    },
    {
      API: 'Food Standards Agency',
      Description: 'UK food hygiene rating data API',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://ratings.food.gov.uk/open-data/en-GB',
      Category: 'Government',
    },
    {
      API: 'Open Government, Australia',
      Description: 'Australian Government Open Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.data.gov.au/',
      Category: 'Government',
    },
    {
      API: 'Open Government, Belgium',
      Description: 'Belgium Government Open Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://data.gov.be/',
      Category: 'Government',
    },
    {
      API: 'Open Government, Canada',
      Description: 'Canadian Government Open Data',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://open.canada.ca/en',
      Category: 'Government',
    },
    {
      API: 'Open Government, France',
      Description: 'French Government Open Data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.data.gouv.fr/',
      Category: 'Government',
    },
    {
      API: 'Open Government, India',
      Description: 'Indian Government Open Data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://data.gov.in/',
      Category: 'Government',
    },
    {
      API: 'Open Government, Italy',
      Description: 'Italy Government Open Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.dati.gov.it/',
      Category: 'Government',
    },
    {
      API: 'Open Government, New Zealand',
      Description: 'New Zealand Government Open Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.data.govt.nz/',
      Category: 'Government',
    },
    {
      API: 'Open Government, Romania',
      Description: 'Romania Government Open Data',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://data.gov.ro/',
      Category: 'Government',
    },
    {
      API: 'Open Government, Saudi Arabia',
      Description: 'Saudi Arabia Government Open Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://data.gov.sa',
      Category: 'Government',
    },
    {
      API: 'Open Government, Taiwan',
      Description: 'Taiwan Government Open Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://data.gov.tw/',
      Category: 'Government',
    },
    {
      API: 'Open Government, Thailand',
      Description: 'Thailand Government Open Data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://data.go.th/',
      Category: 'Government',
    },
    {
      API: 'Open Government, UK',
      Description: 'UK Government Open Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://data.gov.uk/',
      Category: 'Government',
    },
    {
      API: 'Open Government, USA',
      Description: 'United States Government Open Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.data.gov/',
      Category: 'Government',
    },
    {
      API: 'Represent by Open North',
      Description: 'Find Canadian Government Representatives',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://represent.opennorth.ca/',
      Category: 'Government',
    },
    {
      API: 'UK government API catalogue',
      Description: 'APIs from UK government organisations',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://alphagov.github.io/api-catalogue',
      Category: 'Government',
    },
    {
      API: 'USAspending.gov',
      Description: 'US federal spending data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.usaspending.gov/',
      Category: 'Government',
    },
    {
      API: 'Coronavirus in the UK',
      Description: 'UK Government coronavirus data, including deaths and cases by region',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://coronavirus.data.gov.uk/details/developers-guide',
      Category: 'Health',
    },
    {
      API: 'Covid-19',
      Description: 'Covid 19 spread, infection and recovery',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://covid19api.com/',
      Category: 'Health',
    },
    {
      API: 'Covid-19',
      Description: 'Covid 19 cases, deaths and recovery per country',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://github.com/M-Media-Group/Covid-19-API',
      Category: 'Health',
    },
    {
      API: 'Covid-19 Government Response',
      Description: 'Government measures tracker to fight against the Covid-19 pandemic',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://covidtracker.bsg.ox.ac.uk',
      Category: 'Health',
    },
    {
      API: 'Diabetes',
      Description: 'Logging and retrieving diabetes information',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://predictbgl.com/api/',
      Category: 'Health',
    },
    {
      API: 'Healthcare.gov',
      Description: 'Educational content about the US Health Insurance Marketplace',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.healthcare.gov/developers/',
      Category: 'Health',
    },
    {
      API: 'TransitLand',
      Description: 'Transit Aggregation',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://transit.land/documentation/datastore/api-endpoints.html',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Atlanta, US',
      Description: 'Marta',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.itsmarta.com/app-developer-resources.aspx',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Auckland, New Zealand',
      Description: 'Auckland Transport',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.at.govt.nz/',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Belgium',
      Description: 'Belgian transport API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://hello.irail.be/api/',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Berlin, Germany',
      Description: 'Third-party VBB API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/derhuerst/vbb-rest/blob/3/docs/index.md',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Bordeaux, France',
      Description: 'Bordeaux Métropole public transport and more (France)',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://opendata.bordeaux-metropole.fr/explore/',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Boston, US',
      Description: 'MBTA API',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'https://mbta.com/developers/v3-api',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Budapest, Hungary',
      Description: 'Budapest public transport API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://bkkfutar.docs.apiary.io',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Chicago, US',
      Description: 'CTA',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.transitchicago.com/developers/',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Czech Republic',
      Description: 'Czech transport API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.chaps.cz/eng/products/idos-internet',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Denver, US',
      Description: 'RTD',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.rtd-denver.com/gtfs-developer-guide.shtml',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Finland',
      Description: 'Finnish transport API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://digitransit.fi/en/developers/ ',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Germany',
      Description: 'Deutsche Bahn (DB) API',
      Auth: 'apiKey',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://data.deutschebahn.com/dataset/api-fahrplan',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Grenoble, France',
      Description: 'Grenoble public transport',
      Auth: '',
      HTTPS: false,
      Cors: 'no',
      Link: 'https://www.metromobilite.fr/pages/opendata/OpenDataApi.html',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Honolulu, US',
      Description: 'Honolulu Transportation Information',
      Auth: 'apiKey',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://hea.thebus.org/api_info.asp',
      Category: 'Transportation',
    },
    {
      API: 'Transport for India',
      Description: 'India Public Transport API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://data.gov.in/sector/transport',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Lisbon, Portugal',
      Description: 'Data about buses routes, parking and traffic',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://emel.city-platform.com/opendata/',
      Category: 'Transportation',
    },
    {
      API: 'Transport for London, England',
      Description: 'TfL API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.tfl.gov.uk',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Manchester, England',
      Description: 'TfGM transport network data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://developer.tfgm.com/',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Paris, France',
      Description: 'RATP Open Data API',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://data.ratp.fr/api/v1/console/datasets/1.0/search/',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Philadelphia, US',
      Description: 'SEPTA APIs',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www3.septa.org/hackathon/',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Sao Paulo, Brazil',
      Description: 'SPTrans',
      Auth: 'OAuth',
      HTTPS: false,
      Cors: 'unknown',
      Link:
        'http://www.sptrans.com.br/desenvolvedores/api-do-olho-vivo-guia-de-referencia/documentacao-api/',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Sweden',
      Description: 'Public Transport consumer',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.trafiklab.se/api',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Switzerland',
      Description: 'Official Swiss Public Transport Open Data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://opentransportdata.swiss/en/',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Switzerland',
      Description: 'Swiss public transport API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://transport.opendata.ch/',
      Category: 'Transportation',
    },
    {
      API: 'Transport for The Netherlands',
      Description: 'NS, only trains',
      Auth: 'apiKey',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.ns.nl/reisinformatie/ns-api',
      Category: 'Transportation',
    },
    {
      API: 'Transport for The Netherlands',
      Description: 'OVAPI, country-wide public transport',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/skywave/KV78Turbo-OVAPI/wiki',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Toronto, Canada',
      Description: 'TTC',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://myttc.ca/developers',
      Category: 'Transportation',
    },
    {
      API: 'Transport for United States',
      Description: 'NextBus API',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.nextbus.com/xmlFeedDocs/NextBusXMLFeed.pdf',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Vancouver, Canada',
      Description: 'TransLink',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.translink.ca/',
      Category: 'Transportation',
    },
    {
      API: 'Transport for Washington, US',
      Description: 'Washington Metro transport API',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.wmata.com/',
      Category: 'Transportation',
    },
    {
      API: 'Uber',
      Description: 'Uber ride requests and price estimation',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://developer.uber.com/products',
      Category: 'Transportation',
    },
    {
      API: 'WhereIsMyTransport',
      Description: 'Platform for public transport data in emerging cities',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.whereismytransport.com/',
      Category: 'Transportation',
    },
    {
      API: 'Bitly',
      Description: 'URL shortener and link management',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'http://dev.bitly.com/get_started.html',
      Category: 'URL Shorteners',
    },
    {
      API: 'CleanURI',
      Description: 'URL shortener service',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://cleanuri.com/docs',
      Category: 'URL Shorteners',
    },
    {
      API: 'ClickMeter',
      Description: 'Monitor, compare and optimize your marketing links',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://support.clickmeter.com/hc/en-us/categories/201474986',
      Category: 'URL Shorteners',
    },
    {
      API: 'LiteLink',
      Description: 'Simple URL Shortener',
      Auth: 'No',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://litelink.ml/',
      Category: 'URL Shorteners',
    },
    {
      API: 'Rebrandly',
      Description: 'Custom URL shortener for sharing branded links',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developers.rebrandly.com/v1/docs',
      Category: 'URL Shorteners',
    },
    {
      API: 'Shrtlnk',
      Description: 'Simple and efficient short link creation',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://shrtlnk.dev/developer',
      Category: 'URL Shorteners',
    },
    {
      API: 'T.LY',
      Description: 'URL shortener API',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://t.ly/docs',
      Category: 'URL Shorteners',
    },
    {
      API: 'TinyUID',
      Description: 'Shorten long URLs',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://tinyuid.com/docs',
      Category: 'URL Shorteners',
    },
    {
      API: 'Zero Width Shortener',
      Description:
        'Shortens URLs using spaces that have zero width, making them invisible to humans',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://docs.zws.im',
      Category: 'URL Shorteners',
    },
    {
      API: 'Brazilian Vehicles and Prices',
      Description: 'Vehicles information from Fundação Instituto de Pesquisas Econômicas - Fipe',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://deividfortuna.github.io/fipe/',
      Category: 'Vehicle',
    },
    {
      API: 'Kelley Blue Book',
      Description: 'Vehicle info, pricing, configuration, plus much more',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'no',
      Link: 'http://developer.kbb.com/#!/data/1-Default',
      Category: 'Vehicle',
    },
    {
      API: 'Mercedes-Benz',
      Description:
        'Telematics data, remotely access vehicle functions, car configurator, locate service dealers',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://developer.mercedes-benz.com/apis',
      Category: 'Vehicle',
    },
    {
      API: 'NHTSA',
      Description: 'NHTSA Product Information Catalog and Vehicle Listing',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://vpic.nhtsa.dot.gov/api/',
      Category: 'Vehicle',
    },
    {
      API: 'Smartcar',
      Description:
        'Lock and unlock vehicles and get data like odometer reading and location. Works on most new cars',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://smartcar.com/docs/',
      Category: 'Vehicle',
    },
    {
      API: 'An API of Ice And Fire',
      Description: 'Game Of Thrones API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://anapioficeandfire.com/',
      Category: 'Video',
    },
    {
      API: 'Breaking Bad',
      Description: 'Breaking Bad API',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://breakingbadapi.com/documentation',
      Category: 'Video',
    },
    {
      API: 'Breaking Bad Quotes',
      Description: 'Some Breaking Bad quotes',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/shevabam/breaking-bad-quotes',
      Category: 'Video',
    },
    {
      API: 'Czech Television',
      Description: 'TV programme of Czech TV',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.ceskatelevize.cz/xml/tv-program/',
      Category: 'Video',
    },
    {
      API: 'Dailymotion',
      Description: 'Dailymotion Developer API',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.dailymotion.com/',
      Category: 'Video',
    },
    {
      API: 'Final Space',
      Description: 'Final Space API',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://finalspaceapi.com/docs/',
      Category: 'Video',
    },
    {
      API: 'Game of Thrones Quotes',
      Description: 'Some Game of Thrones quotes',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://gameofthronesquotes.xyz/',
      Category: 'Video',
    },
    {
      API: 'Harry Potter',
      Description: 'Harry Potter API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.potterapi.com/',
      Category: 'Video',
    },
    {
      API: 'MCU Countdown',
      Description: 'A Countdown to the next MCU Film',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://github.com/DiljotSG/MCU-Countdown',
      Category: 'Video',
    },
    {
      API: 'Open Movie Database',
      Description: 'Movie information',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'http://www.omdbapi.com/',
      Category: 'Video',
    },
    {
      API: 'Ron Swanson Quotes',
      Description: 'Television',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://github.com/jamesseanwright/ron-swanson-quotes#ron-swanson-quotes-api',
      Category: 'Video',
    },
    {
      API: 'STAPI',
      Description: 'Information on all things Star Trek',
      Auth: '',
      HTTPS: false,
      Cors: 'no',
      Link: 'http://stapi.co',
      Category: 'Video',
    },
    {
      API: 'SWAPI',
      Description: "All the Star Wars data you've ever wanted",
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://swapi.dev/',
      Category: 'Video',
    },
    {
      API: 'SWAPI',
      Description: 'All things Star Wars',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.swapi.tech',
      Category: 'Video',
    },
    {
      API: 'The Lord of the Rings',
      Description: 'The Lord of the Rings API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://the-one-api.dev/',
      Category: 'Video',
    },
    {
      API: 'The Vampire Diaries',
      Description: 'TV Show Data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://vampire-diaries-api.netlify.app/',
      Category: 'Video',
    },
    {
      API: 'TMDb',
      Description: 'Community-based movie data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.themoviedb.org/documentation/api',
      Category: 'Video',
    },
    {
      API: 'Trakt',
      Description: 'Movie and TV Data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://trakt.tv/b/api-docs',
      Category: 'Video',
    },
    {
      API: 'TVDB',
      Description: 'Television data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.thetvdb.com/swagger',
      Category: 'Video',
    },
    {
      API: 'TVMaze',
      Description: 'TV Show Data',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.tvmaze.com/api',
      Category: 'Video',
    },
    {
      API: 'Vimeo',
      Description: 'Vimeo Developer API',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.vimeo.com/',
      Category: 'Video',
    },
    {
      API: 'YouTube',
      Description: 'Add YouTube functionality to your sites and apps',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developers.google.com/youtube/',
      Category: 'Video',
    },
    {
      API: 'YTS',
      Description: 'Movie Data',
      Auth: '',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://yts.mx/api',
      Category: 'Video',
    },
    {
      API: '7Timer!',
      Description: 'Weather, especially for Astroweather',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://www.7timer.info/doc.php?lang=en',
      Category: 'Weather',
    },
    {
      API: 'APIXU',
      Description: 'Weather',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.apixu.com/doc/request.aspx',
      Category: 'Weather',
    },
    {
      API: 'ColorfulClouds',
      Description: 'Weather',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://open.caiyunapp.com/ColorfulClouds_Weather_API',
      Category: 'Weather',
    },
    {
      API: 'Dark Sky',
      Description: 'Weather',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://darksky.net/dev/',
      Category: 'Weather',
    },
    {
      API: 'Foreca',
      Description: 'Weather',
      Auth: 'OAuth',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://developer.foreca.com',
      Category: 'Weather',
    },
    {
      API: 'MetaWeather',
      Description: 'Weather',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://www.metaweather.com/api/',
      Category: 'Weather',
    },
    {
      API: 'Meteorologisk Institutt',
      Description: 'Weather and climate data',
      Auth: 'User-Agent',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://api.met.no/weatherapi/documentation',
      Category: 'Weather',
    },
    {
      API: 'NOAA Climate Data',
      Description: 'Weather and climate data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.ncdc.noaa.gov/cdo-web/',
      Category: 'Weather',
    },
    {
      API: 'ODWeather',
      Description: 'Weather and weather webcams',
      Auth: '',
      HTTPS: false,
      Cors: 'unknown',
      Link: 'http://api.oceandrivers.com/static/docs.html',
      Category: 'Weather',
    },
    {
      API: 'openSenseMap',
      Description: 'Data from Personal Weather Stations called senseBoxes',
      Auth: '',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://api.opensensemap.org/',
      Category: 'Weather',
    },
    {
      API: 'OpenUV',
      Description: 'Real-time UV Index Forecast',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.openuv.io',
      Category: 'Weather',
    },
    {
      API: 'OpenWeatherMap',
      Description: 'Weather',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://openweathermap.org/api',
      Category: 'Weather',
    },
    {
      API: 'QWeather',
      Description: 'Location-based weather data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://dev.qweather.com/',
      Category: 'Weather',
    },
    {
      API: 'Storm Glass',
      Description: 'Global marine weather from multiple sources',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://stormglass.io/',
      Category: 'Weather',
    },
    {
      API: 'TheRainery',
      Description: 'Forecast models from meteorological institutes',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://therainery.com/documentation/',
      Category: 'Weather',
    },
    {
      API: 'Troposphere',
      Description: 'Global weather and climate data',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'yes',
      Link: 'https://www.troposphere.io/developer',
      Category: 'Weather',
    },
    {
      API: 'weather-api',
      Description: 'A RESTful free API to check the weather',
      Auth: '',
      HTTPS: true,
      Cors: 'no',
      Link: 'https://github.com/robertoduessmann/weather-api',
      Category: 'Weather',
    },
    {
      API: 'Weatherbit',
      Description: 'Weather',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://www.weatherbit.io/api',
      Category: 'Weather',
    },
    {
      API: 'weatherstack',
      Description: 'Real-Time \u0026 Historical World Weather Data API',
      Auth: 'apiKey',
      HTTPS: true,
      Cors: 'unknown',
      Link: 'https://weatherstack.com/',
      Category: 'Weather',
    },
  ],
};
